// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Importador.Repositorio.Migrations
{
    [DbContext(typeof(AplicacaoContexto))]
    [Migration("20240830052210_MigrationInicial")]
    partial class MigrationInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Importador.Dominio.Entidades.Catalago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Catalago", (string)null);
                });

            modelBuilder.Entity("Importador.Dominio.Entidades.CatalagoColuna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCatalago")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdCatalago");

                    b.ToTable("CatalagoColuna", (string)null);
                });

            modelBuilder.Entity("Importador.Dominio.Entidades.DadosCatalago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCatalagoColuna")
                        .HasColumnType("int");

                    b.Property<int>("Linhas")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IdCatalagoColuna");

                    b.ToTable("DadosCatalago", (string)null);
                });

            modelBuilder.Entity("Importador.Dominio.Entidades.CatalagoColuna", b =>
                {
                    b.HasOne("Importador.Dominio.Entidades.Catalago", "Catalago")
                        .WithMany("Colunas")
                        .HasForeignKey("IdCatalago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalago");
                });

            modelBuilder.Entity("Importador.Dominio.Entidades.DadosCatalago", b =>
                {
                    b.HasOne("Importador.Dominio.Entidades.CatalagoColuna", "CatalagoColuna")
                        .WithMany("DadosCatalagos")
                        .HasForeignKey("IdCatalagoColuna")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalagoColuna");
                });

            modelBuilder.Entity("Importador.Dominio.Entidades.Catalago", b =>
                {
                    b.Navigation("Colunas");
                });

            modelBuilder.Entity("Importador.Dominio.Entidades.CatalagoColuna", b =>
                {
                    b.Navigation("DadosCatalagos");
                });
#pragma warning restore 612, 618
        }
    }
}
